credentials:
  usernames:
    Admin:
      email: welvision@gmail.com
      name: Admin
      password: $2b$12$l8Z6GqTLcT8GfXz70d5fJeOSk3T4NemDrll0OGF2q0moN8gQ7Dsq2
    Operator:
      email: welvision@gmail.com
      name: Operator
      password: $2b$12$joyUJgtY0fZsvLLdf6Cwr.I9Iuui45MpWDAhIsw5nwaiZt.E1pyBS
cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - iqube@gmail.com
